const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../session-core.js');
function lesson(){return {crossword:{words:Array.from({length:5},(_,i)=>({answer:'ABC',r:i,c:0,dir:'across'}))},errors:Array.from({length:5},()=>({correct:1,options:['A','B','C']})),algorithms:Array.from({length:1},()=>({steps:['a','b','c']}))};}
function active(){return C.beginStage(C.createAttempt(' Ali Valiyev ','8-A'),1000);}
test('join validates pupil name and class and does not start timer',()=>{assert.throws(()=>C.createAttempt('','8-A'));assert.throws(()=>C.createAttempt('Ali',''));const a=C.createAttempt(' Ali Valiyev ','8-A');assert.equal(a.name,'Ali Valiyev');assert.equal(a.status,'ready');assert.equal(a.deadline,null);});
test('each stage gets exactly 300 seconds only after Start',()=>{let a=active();assert.equal(a.deadline,301000);assert.equal(C.remaining(a,1000),300);assert.equal(C.remaining(a,300999),1);assert.equal(C.remaining(a,301000),0);a=C.finishStage(a,lesson(),301000);assert.equal(a.status,'ready');assert.equal(a.stage,1);assert.equal(a.deadline,null);a=C.beginStage(a,900000);assert.equal(a.deadline,1200000);});
test('count full words, never individual correct letters',()=>{let a=active();for(const [k,v] of Object.entries({'0,0':'A','0,1':'B','0,2':'C','1,0':'A','1,1':'B'}))a=C.record(a,k,v,2000);a=C.finishStage(a,lesson(),3000);assert.equal(a.scores[0],2);});
test('late edits rejected, exact deadline automatically grades',()=>{let a=active();assert.equal(C.record(a,'0,0','A',301000),a);assert.equal(C.canEdit(a,301000),false);a=C.finishStage(a,lesson(),301000);assert.equal(a.reasons[0],'timeout');assert.equal(a.scores[0],0);});
test('stages cannot be skipped or scored twice',()=>{let a=C.createAttempt('Ali','8-A');assert.equal(C.finishStage(a,lesson(),0),a);a=C.beginStage(a,1000);assert.equal(C.beginStage(a,2000),a);a=C.finishStage(a,lesson(),3000);assert.equal(C.finishStage(a,lesson(),4000),a);assert.throws(()=>C.result(a));});
test('five error questions award ten points and unanswered do not count as option zero',()=>{let a=C.finishStage(active(),lesson(),2000);a=C.beginStage(a,3000);for(let i=0;i<5;i++)a=C.record(a,i,1,4000);a=C.finishStage(a,lesson(),5000);assert.equal(a.scores[1],10);assert.equal(C.grade(lesson(),1,{}),0);});
test('algorithm gives ten points for a completely correct sequence',()=>{assert.equal(C.grade(lesson(),2,{0:[0,1,2],1:[0,2,1],2:[0,1]}),10);assert.equal(C.grade(lesson(),2,{0:[0,0,2]}),0);});
test('last timeout produces final result without another Start',()=>{let a=active();a=C.finishStage(a,lesson(),301000);a=C.beginStage(a,700000);a=C.finishStage(a,lesson(),1300000);a=C.beginStage(a,1400000);a=C.finishStage(a,lesson(),2000000);assert.equal(a.status,'finished');assert.equal(C.result(a).total,0);assert.equal(C.result(a).average,0);assert.equal(C.result(a).name,'Ali Valiyev');assert.equal(C.result(a).classroom,'8-A');assert.equal(C.record(a,1,1,2000001),a);});
test('sum and mean are computed from all three scores',()=>{const r=C.result({status:'finished',scores:[8,7,5],name:'Ali',classroom:'8-A'});assert.equal(r.total,20);assert.equal(r.average,20/3);assert.equal(r.maxTotal,30);assert.equal(r.maxAverage,10);});
test('all-correct outcome is 30 total and 10 mean',()=>{const r=C.result({status:'finished',scores:[10,10,10],name:'Ali',classroom:'8-A'});assert.equal(r.total,30);assert.equal(r.average,10);});
test('malformed answers and empty names cannot create points',()=>{assert.equal(C.grade(lesson(),1,{0:'1',1:null,2:99}),0);assert.throws(()=>C.createAttempt('a','8-A'));assert.throws(()=>C.createAttempt('a'.repeat(71),'8-A'));});
